### ISSUE TITLE
SEP purls do not resolve

### ISSUE THREAD

**Issue by cmungall** [stuchalk/scidata#14]
https://stuchalk.github.io/scidata/contexts/scidata_chemical.jsonld

has
obo:sep_00088

normally OBO PURLs have ontology IDs, e.g. obo:SEP_00088

either way this doesn't resolve, looks like SEP is marked as deprecated (see https://github.com/OBOFoundry/OBOFoundry.github.io/pull/847)

http://obofoundry.org/ontology/sep

If you think it should revived you can raise an issue: https://github.com/OBOFoundry/OBOFoundry.github.io/issues

otherwise I recommend using a different ontology like OBI

**Comment by stuchalk** [comment]
Thanks for spotting these!  I have replaced them with NCIT equivalents in commit bb95b72.
